{
  imports = [
    ./hardware-configuration.nix
    ./app/gamemode.nix
    ./app/nixvim/nixvim.nix
    ./app/nm.nix
    ./app/thunar.nix
    ./app/virtmanager.nix
    ./hardware/sound.nix
    ./hardware/zram.nix
    ./hardware/trim.nix
    ./hardware/bluetooth.nix
    ./security/blocklist.nix
    ./security/doas.nix
    ./security/firewall.nix
    ./security/gpg.nix
    ./security/openvpn.nix
    ./style/stylix.nix
    ./sysconf/env.nix
    ./sysconf/packages.nix
    ./sysconf/user.nix
    ./sysconf/xserver.nix
    ./wm/hyprland.nix
  ];
}
